### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by timbod7** [capital-match/yodlee-hs#1]
A google search turned up this repo, which is timely for some work I am considering.

What is the status of the project?

**Comment by kccqzy** [comment]
This project can be considered abandoned. In the end we decided not to utilise Yodlee because it didn't meet our expectations and there was no point in continuing development. The existing code should be considered in the early stage of development: it can log in if no MFA is required, and not much else. Feel free to fork it and continue development.

**Comment by timbod7** [comment]
Thanks
